set_property PACKAGE_PIN M15 [get_ports B3]
set_property PACKAGE_PIN H17 [get_ports B2]
set_property PACKAGE_PIN H18 [get_ports B1]
set_property PACKAGE_PIN H19 [get_ports B0]
set_property PACKAGE_PIN F21 [get_ports A3]
set_property PACKAGE_PIN H22 [get_ports A2]
set_property PACKAGE_PIN G22 [get_ports A1]
set_property PACKAGE_PIN F22 [get_ports A0]
set_property PACKAGE_PIN U14 [get_ports less_in]
set_property PACKAGE_PIN U19 [get_ports equal_in]
set_property PACKAGE_PIN W22 [get_ports greater_in]

set_property PACKAGE_PIN U14 [get_ports less_out]
set_property PACKAGE_PIN U19 [get_ports equal_out]
set_property PACKAGE_PIN W22 [get_ports greater_out]


set_property IOSTANDARD LVCMOS33 [get_ports B0]
set_property IOSTANDARD LVCMOS33 [get_ports B1]
set_property IOSTANDARD LVCMOS33 [get_ports B2]
set_property IOSTANDARD LVCMOS33 [get_ports B3]
set_property IOSTANDARD LVCMOS33 [get_ports A3]
set_property IOSTANDARD LVCMOS33 [get_ports A2]
set_property IOSTANDARD LVCMOS33 [get_ports A1]
set_property IOSTANDARD LVCMOS33 [get_ports A0]
set_property IOSTANDARD LVCMOS33 [get_ports less_in]
set_property IOSTANDARD LVCMOS33 [get_ports equal_in]
set_property IOSTANDARD LVCMOS33 [get_ports greater_in]
set_property IOSTANDARD LVCMOS33 [get_ports less_out]
set_property IOSTANDARD LVCMOS33 [get_ports equal_out]
set_property IOSTANDARD LVCMOS33 [get_ports greater_out]
